name: C++ GA Testing

on:
  push:
    branches: [ main ]

jobs:
  ga-test:
    name: Solve D2D for ${{ matrix.problem }} with Dronetype ${{ matrix.dronetype }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        problem: ["10.10.1", "10.10.2", "10.10.3", "10.10.4"]
        dronetype: ["1", "2", "3", "4"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make python3
    - name: Setup Data Directories
      run: |
        mkdir -p "D2D Problem/random_data"
    - name: Compile C++ Program
      run: |
        g++ -std=c++17 -O3 sol.cpp src/*.cpp -o test.exe
    - name: Run Program and Aggregate Results
      id: run_program
      run: |
        export DRONETYPE="${{ matrix.dronetype }}"
        export GITHUB_JOB="${{ github.job }}"
        export DATA_FILE="D2D Problem/random_data/${{ matrix.problem }}.txt"
        if [ -f "$DATA_FILE" ]; then
          echo "Data file $DATA_FILE found. Running the program..."
          ./test.exe -dronetype "${{ matrix.dronetype }}" "${{ matrix.problem }}" | python3 summary.py
        else
          echo "Data file $DATA_FILE not found. Skipping program execution."
        fi
    - name: Upload Individual Results
      uses: actions/upload-artifact@v3
      with:
        name: individual-results-${{ matrix.problem }}-${{ matrix.dronetype }}
        path: results.csv

  upload-results:
    name: Upload Combined Results
    runs-on: ubuntu-latest
    needs: ga-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download All Individual Results
        uses: actions/download-artifact@v3
        with:
          pattern: individual-results-*
          merge-artifacts: false

      - name: Combine Results
        run: |
          # Tạo file tổng hợp với tiêu đề chính xác
          echo "Dronetype,Thoi Gian,Route,Problem" > combined_results.csv

          # Duyệt qua tất cả thư mục chứa kết quả
          find . -maxdepth 1 -type d -name "individual-results-*" -print0 | while IFS= read -r -d $'\0' dir; do
            artifact_name=$(basename "$dir")
            IFS="-" read -r -a parts <<< "${artifact_name#individual-results-}"
            dronetype="${parts[1]}"
            results_file="$dir/results.csv"

            if [ -f "$results_file" ]; then
              # Đọc từng dòng và bỏ qua các dòng trống hoặc không hợp lệ
              tail -n +2 "$results_file" | while IFS= read -r line; do
                  echo "${dronetype},${line}" >> combined_results.csv
              done
            else
              echo "File $results_file does not exist. Skipping."
            fi
          done



      - name: Upload Combined Results
        uses: actions/upload-artifact@v3
        with:
          name: combined-results
          path: combined_results.csv
