name: C++ GA Testing

on:
  push:
    branches: [ main ]

jobs:
  ga-test:
    name: Solve D2D for ${{ matrix.problem }} with Dronetype ${{ matrix.dronetype }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        problem: ["6.5.1", "6.5.2", "6.5.3", "6.5.4", "6.10.1", "6.10.2", "6.10.3", "6.10.4", "10.10.1", "10.10.2", "10.10.3", "10.10.4"]
        dronetype: ["1", "2", "3","4"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make python3

    - name: Setup Data Directories
      run: |
        mkdir -p "D2D Problem/random_data"

    - name: Compile C++ Program
      run: |
        g++ -std=c++17 -O3 sol.cpp src/*.cpp -o test.exe

    - name: Run Program and Aggregate Results
      id: run_program
      run: |
        export DRONETYPE="${{ matrix.dronetype }}"
        export GITHUB_JOB="${{ github.job_name }}"
        DATA_FILE="D2D Problem/random_data/${{ matrix.problem }}.txt"
        if [ -f "$DATA_FILE" ]; then
          echo "Data file $DATA_FILE found. Running the program..."
          ./test.exe -dronetype "${{ matrix.dronetype }}" "${{ matrix.problem }}" | python3 summary.py
        else
          echo "Data file $DATA_FILE not found. Skipping program execution."
        fi

    - name: Upload Individual Results
      uses: actions/upload-artifact@v3
      with:
        name: individual-results-${{ matrix.problem }}-${{ matrix.dronetype }}
        path: results.csv

  upload-results:
    name: Upload Combined Results
    runs-on: ubuntu-latest
    needs: ga-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug: Check current directory before download
        run: pwd

      - name: Download All Individual Results
        id: download_artifacts
        uses: actions/download-artifact@v3
        with:
          pattern: individual-results-*
          merge-artifacts: false
          path: combined_results
          if-not-exists: true

      - name: Debug: List files after download
        run: |
          echo "Files and directories in the current directory after download:"
          ls -la
          echo "Files and directories in combined_results (if it exists):"
          ls -la combined_results || true # In lỗi nếu thư mục không tồn tại

      - name: List Downloaded Files - Detailed
        run: |
          echo "Checking if combined_results directory exists..."
          if [ -d "combined_results" ]; then
            echo "combined_results directory exists."
            echo "Listing files in combined_results:"
            find combined_results -print
          else
            echo "combined_results directory does not exist!"
          fi
        shell: /usr/bin/bash -e {0}

      - name: Create Combined Results File with Header
        run: |
          echo "Creating combined_results.csv with header..."
          echo "Dronetype,Thoi Gian,Route,Job Name" > combined_results.csv
          echo "combined_results.csv created."

      - name: Combine Results - Debugging
        run: |
          echo "Starting Combine Results - Debugging"
          find combined_results -name "results.csv" -print0 | while IFS= read -r -d $'\0' file; do
            echo "Processing file: $file"

            # Lấy thông tin từ tên artifact
            artifact_name=$(basename $(dirname "$file"))
            echo "Artifact name: $artifact_name"
            IFS="-" read -r -a parts <<< "$artifact_name"
            echo "Parts: ${parts[@]}"
            problem="${parts[2]}"
            dronetype="${parts[3]}"
            echo "Problem: $problem, Dronetype: $dronetype"
            job_name="Solve D2D for ${problem} with Dronetype ${dronetype}"
            echo "Job Name: $job_name"

            # Extract data row and add Dronetype and Job Name
            echo "Processing data from $file"
            awk -F',' 'NR==2 {print ENVIRON["DRONETYPE"], $2, $3, ENVIRON["PROBLEM"]}' ENVIRON[PROBLEM]="${problem}" "$file" >> combined_results.csv
            echo "Appended data to combined_results.csv"
            echo "-------------------------"
          done
          echo "Finished Combine Results - Debugging"

      - name: Debug: Check if combined_results.csv was created
        run: |
          echo "Checking if combined_results.csv exists:"
          if [ -f "combined_results.csv" ]; then
            echo "combined_results.csv exists."
            echo "Contents of combined_results.csv:"
            cat combined_results.csv
          else
            echo "combined_results.csv does not exist!"
          fi

      - name: Upload Combined Results
        uses: actions/upload-artifact@v3
        with:
          name: combined-results
          path: combined_results.csv