name: C++ GA Testing

on:
  push:
    branches: [ main ]

jobs:
  ga-test:
    name: Solve D2D for ${{ matrix.problem }} - Drone ${{ matrix.dronetype }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        problem: ["6.5.1", "6.5.2", "6.5.3", "6.5.4", "6.10.1", "6.10.2", "6.10.3", "6.10.4", "10.10.1", "10.10.2", "10.10.3", "10.10.4"]
        dronetype: ["1", "2", "3","4"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Setup Data Directories
      run: |
        mkdir -p "D2D Problem/random_data"

    - name: Compile C++ Program
      run: |
        g++ -std=c++17  -O3 sol.cpp src/*.cpp -o test.exe

    - name: Run Program and Save Result
      run: |
        PROBLEM_NAME="${{ matrix.problem }}"
        DRONE_TYPE="${{ matrix.dronetype }}"
        DATA_FILE="D2D Problem/random_data/${PROBLEM_NAME}.txt"
        OUTPUT_FILE="result_${PROBLEM_NAME}_${DRONE_TYPE}.csv"

        if [ -f "$DATA_FILE" ]; then
          echo "Running program for $PROBLEM_NAME with drone type $DRONE_TYPE..."
          ./test.exe -dronetype "$DRONE_TYPE" "$PROBLEM_NAME" > "$OUTPUT_FILE"
          echo "Result saved to $OUTPUT_FILE"
        else
          echo "Data file $DATA_FILE not found. Skipping program execution."
          echo "problem,dronetype,error" > "$OUTPUT_FILE"
          echo "$PROBLEM_NAME,$DRONE_TYPE,data_file_not_found" >> "$OUTPUT_FILE"
        fi

    - name: Upload Result Artifact
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: result_*.csv

  aggregate-results:
    name: Aggregate Results
    needs: ga-test
    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v3
      with:
        name: results
        path: all_results

    - name: Combine Results into Single CSV
      run: |
        cd all_results
        awk 'FNR == 1 && NR > 1 { next } { print }' *.csv > combined_results.csv
        
    - name: Upload Combined Results Artifact
      uses: actions/upload-artifact@v3
      with:
        name: combined-results
        path: all_results/combined_results.csv