name: C++ GA Testing

on:
  push:
    branches: [ main ]

jobs:
  ga-test:
    name: Solve D2D for ${{ matrix.problem }} with Dronetype ${{ matrix.dronetype }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        problem: ["6.5.1", "6.5.2", "6.5.3", "6.5.4", "6.10.1", "6.10.2", "6.10.3", "6.10.4", "10.10.1", "10.10.2", "10.10.3", "10.10.4"]
        dronetype: ["1", "2", "3","4"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make python3
    - name: Setup Data Directories
      run: |
        mkdir -p "D2D Problem/random_data"
    - name: Compile C++ Program
      run: |
        g++ -std=c++17 -O3 sol.cpp src/*.cpp -o test.exe
    - name: Run Program and Aggregate Results
      id: run_program
      run: |
        export DRONETYPE="${{ matrix.dronetype }}"
        export GITHUB_JOB="${{ github.job_name }}"
        DATA_FILE="D2D Problem/random_data/${{ matrix.problem }}.txt"
        if [ -f "$DATA_FILE" ]; then
          echo "Data file $DATA_FILE found. Running the program..."
          ./test.exe -dronetype "${{ matrix.dronetype }}" "${{ matrix.problem }}" | python3 summary.py
        else
          echo "Data file $DATA_FILE not found. Skipping program execution."
        fi
    - name: Upload Individual Results
      uses: actions/upload-artifact@v3
      with:
        name: individual-results-${{ matrix.problem }}-${{ matrix.dronetype }}
        path: results.csv

  upload-results:
    name: Upload Combined Results
    runs-on: ubuntu-latest
    needs: ga-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download All Individual Results
        uses: actions/download-artifact@v3
        with:
          pattern: individual-results-*
          merge-artifacts: false # Không merge, để mỗi artifact ở thư mục riêng

      - name: Create Combined Results File with Header
        run: |
          echo "Dronetype,Thoi Gian,Route,Job Name" > combined_results.csv
      - name: Combine Results
        run: |
          find . -name "results.csv" -exec sh -c '
            # Lấy thông tin từ tên artifact
            artifact_name=$(dirname "{}")
            IFS="-" read -r -a parts <<< "$artifact_name"
            problem="${parts[2]}"
            dronetype="${parts[3]}"
            job_name="Solve D2D for ${problem} with Dronetype ${dronetype}"
            # Đọc dữ liệu từ file và thêm thông tin
            tail -n +2 "{}" | awk -v dt="${dronetype}" -v jn="${job_name}" '{print dt","$0","jn}' >> combined_results.csv
          ' \;
      - name: Upload Combined Results
        uses: actions/upload-artifact@v3
        with:
          name: combined-results
          path: combined_results.csv